# Finding Pattern

In [1]:
import numpy as np

## Given this array, find the next number in the sequence

In [2]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

##### for information about numpy.diff, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html

In [3]:
np.diff(my_teaser_array)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [4]:
np.diff(my_teaser_array, n=2)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [5]:
np.diff(my_teaser_array, n=3)

array([0, 0, 0, 0, 0, 0, 0, 0])

##### Warning: imports should (usually) appear at top of notebook

If SymPy is not included on your computer; open a console and type 'conda sympy'

In [6]:
import sympy as sm
sm

<module 'sympy' from '/Users/arugupta/anaconda3/lib/python3.6/site-packages/sympy/__init__.py'>

In [7]:
sm.init_session()

MultipleInstanceError: Multiple incompatible subclass instances of TerminalInteractiveShell are being created.

In [ ]:
diff(x**3)

In [ ]:
diff(x**3, x, 2)

In [ ]:
diff(x**3, x, 3)

In [ ]:
diff(x**3, x, 4)

In [ ]:
def my_guess(n):
    return (n+1)**3 - n**3

In [ ]:
my_guess(np.arange(20))

In [ ]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array